"""Added last_login column to User model

Revision ID: 066e4d41f8ab
Revises: 
Create Date: 2025-03-14 12:49:57.319698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066e4d41f8ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
